#!/usr/bin/bash -ve

export WORKSPACE_BASE=/mnt/c/dev/OpenHands

docker run \
 -it \
 --rm \
 -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.26-nikolaik \
 -e LOG_ALL_EVENTS=true \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v ~/.openhands-state:/.openhands-state \
 -e SANDBOX_USER_ID=$(id -u) \
 -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
 -v $WORKSPACE_BASE:/opt/workspace_base \
 -p 3000:3000 \
 --add-host host.docker.internal:host-gateway \
 --name openhands-app \
docker.all-hands.dev/all-hands-ai/openhands:0.26
